name: Build and Push Docker Images

on:
  push:
    branches:
      - develop

env:
  REGISTRY: "registry.digitalocean.com/sigil"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [op-node, op-batcher, op-proposer]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build container image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.component }}
          file: ./${{ matrix.component }}/Dockerfile
          push: false
          tags: ${{ env.REGISTRY }}/${{ matrix.component }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 1200

      - name: Push image to DO Container Registry
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.component }}
          file: ./${{ matrix.component }}/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ matrix.component }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ matrix.component }}:latest
